#version: '3.7'
#
#services:
#  web:
#    build: ./
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/usr/scr/app
#    ports:
#      - 8000:8000
#    env_file:
#      - ./.env.dev
#  db:
#    image: postgres:12.0-alpine
#    volumes:
#      - pg_data:/var/lib/postgresql/data/
#    environment:
#      POSTGRES_PASSWORD: 1212
#      POSTGRES_USER: postgres
#      POSTGRES_DB: postgres
#volumes:
#  pg_data:

version: '3.7'

services:
  dm_db:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 1212
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  django:
    container_name: dm_movie
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/dm_rest/manage.py migrate --noinput &&
             python /usr/src/dm_rest/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/dm_rest
    ports:
      - 8000:8000
    depends_on:
      - dm_db
volumes:
  pg_data: