version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn django_movie.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  vue:
    build:
      context: ../../django_vue
      dockerfile: Dockerfile.prod
    volumes:
    - vue_dist:/app/dist
    depends_on:
      - web
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - vue_dist:/app/dist
    depends_on:
      - web
      - vue
volumes:
  pg_data:
  static_volume:
  media_volume:
  vue_dist:
